"""Google Gemini API integration service."""
import asyncio
from io import BytesIO
from typing import Optional
from PIL import Image
from google import genai
from google.genai import types

from app.config import settings


# Initialize Gemini client
client = genai.Client(
    api_key=settings.gemini_api_key,
    http_options={"api_version": "v1alpha"}
) if settings.gemini_api_key else None


def _normalize_media_resolution(value: Optional[str], default: str = "media_resolution_high") -> str:
    """Normalize a configured media resolution string."""
    if not value:
        return default

    normalized = str(value).strip().lower()
    if not normalized.startswith("media_resolution_"):
        normalized = f"media_resolution_{normalized}"

    allowed = {"media_resolution_low", "media_resolution_medium", "media_resolution_high"}
    if normalized not in allowed:
        return default
    return normalized


MEDIA_RESOLUTION_LEVEL = _normalize_media_resolution(settings.gemini_media_resolution)


async def enhance_image(
    sprite_image: bytes,
    enhancement_prompt: str,
    style: str = "photorealistic"
) -> bytes:
    """
    Enhance sprite image using Gemini image generation.

    Args:
        sprite_image: Original sprite image bytes
        enhancement_prompt: Text prompt for enhancement
        style: Style preset (photorealistic, fantasy, etc.)

    Returns:
        bytes: Enhanced PNG image data
    """
    if not client:
        raise ValueError("Gemini API key not configured")

    # Style presets
    style_prompts = {
        "photorealistic": "Transform this into a photorealistic, highly detailed image:",
        "fantasy": "Transform this into detailed fantasy artwork:",
        "comic": "Transform this into comic book style illustration:",
        "cyberpunk": "Transform this into a cyberpunk style image:",
        "medieval": "Transform this into a medieval fantasy style:",
    }

    style_prefix = style_prompts.get(style, style_prompts["photorealistic"])
    full_prompt = f"{style_prefix} {enhancement_prompt}"

    # Normalize incoming image bytes to PNG for Gemini
    image = Image.open(BytesIO(sprite_image))
    buffered = BytesIO()
    image.save(buffered, format='PNG')
    sprite_bytes = buffered.getvalue()

    contents = [
        types.Part(
            inline_data=types.Blob(
                mime_type='image/png',
                data=sprite_bytes
            ),
            media_resolution={"level": MEDIA_RESOLUTION_LEVEL}
        ),
        full_prompt
    ]

    generation_config = types.GenerateContentConfig(
        media_resolution={"level": MEDIA_RESOLUTION_LEVEL}
    )

    response = await asyncio.to_thread(
        client.models.generate_content,
        model='gemini-2.5-flash-image',
        contents=contents,
        config=generation_config
    )

    for candidate in getattr(response, "candidates", []):
        content = getattr(candidate, "content", None)
        if not content:
            continue
        for part in getattr(content, "parts", []):
            if getattr(part, "inline_data", None):
                output = BytesIO()
                Image.open(BytesIO(part.inline_data.data)).save(output, format='PNG')
                return output.getvalue()

    raise ValueError("No image generated by Gemini")
