"""Initial schema with image assets and scene cache

Revision ID: 1a73ac545ec4
Revises: 
Create Date: 2025-10-24 18:21:41.331197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a73ac545ec4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.Column('storage_path_full', sa.String(length=500), nullable=False),
    sa.Column('storage_path_thumbnail', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=10), nullable=False),
    sa.Column('generation_time_ms', sa.Integer(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path_full')
    )
    op.create_index('idx_active', 'image_assets', ['deleted_at'], unique=False)
    op.create_index('idx_component_lookup', 'image_assets', ['component', 'subject_name'], unique=False)
    op.create_index('idx_featured', 'image_assets', ['subject_name', 'is_featured'], unique=False)
    op.create_index('idx_subject_lookup', 'image_assets', ['subject_type', 'subject_name'], unique=False)
    op.create_index(op.f('ix_image_assets_subject_name'), 'image_assets', ['subject_name'], unique=False)
    op.create_table('scene_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('time_of_day', sa.String(length=50), nullable=False),
    sa.Column('weather', sa.String(length=50), nullable=False),
    sa.Column('image_asset_id', sa.Integer(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_asset_id'], ['image_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cache_key', 'scene_cache', ['location', 'time_of_day', 'weather'], unique=False)
    op.create_index('idx_expiry', 'scene_cache', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_expiry', table_name='scene_cache')
    op.drop_index('idx_cache_key', table_name='scene_cache')
    op.drop_table('scene_cache')
    op.drop_index(op.f('ix_image_assets_subject_name'), table_name='image_assets')
    op.drop_index('idx_subject_lookup', table_name='image_assets')
    op.drop_index('idx_featured', table_name='image_assets')
    op.drop_index('idx_component_lookup', table_name='image_assets')
    op.drop_index('idx_active', table_name='image_assets')
    op.drop_table('image_assets')
    # ### end Alembic commands ###
